#!/usr/bin/env python


__version__ = "1"


"""
pynote - A tiny ncurses note/todo tool
Copyright (c) 2005 Kai Kuehne <pynote@kai-kuehne.de>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
"""

import getopt
import os
import sys



########################################
class Pynote:
########################################
    def print_help(self):
        print "Help"
        print

    def print_version(self):
        print "pynote " + __version__ + " (c) by Kai Kuehne <kk@cvmx.net>"
        print


########################################
def main():
########################################
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hv")
    except:
        #usage = _("Usage: %s -h \n")
        usage = "Usage: %s [-hv] \n"
        sys.stderr.write(usage % sys.argv[0])
        sys.exit(1)

    global pynote
    pynote = Pynote()

    try:
        for opt, optarg in opts:
            if opt == "-h": pynote.print_help()
            if opt == "-v": pynote.print_version()
    except Exception:
        import traceback
        traceback.print_exc()


if __name__ == "__main__": main()

